/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStockCompany,
  IMetaStockCompanyInterface,
} from "../IMetaStockCompany";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "createMetaStockCompany",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMetaStockCompany__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStockCompanyInterface {
    return new utils.Interface(_abi) as IMetaStockCompanyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStockCompany {
    return new Contract(address, _abi, signerOrProvider) as IMetaStockCompany;
  }
}
