/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStocksFranchise,
  IMetaStocksFranchiseInterface,
} from "../IMetaStocksFranchise";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStocksFranchise__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStocksFranchiseInterface {
    return new utils.Interface(_abi) as IMetaStocksFranchiseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStocksFranchise {
    return new Contract(address, _abi, signerOrProvider) as IMetaStocksFranchise;
  }
}
