/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStockFranchiseShare,
  IMetaStockFranchiseShareInterface,
} from "../IMetaStockFranchiseShare";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStockFranchiseShare__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStockFranchiseShareInterface {
    return new utils.Interface(_abi) as IMetaStockFranchiseShareInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStockFranchiseShare {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMetaStockFranchiseShare;
  }
}
