/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStockFranchise,
  IMetaStockFranchiseInterface,
} from "../IMetaStockFranchise";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStockFranchise__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStockFranchiseInterface {
    return new utils.Interface(_abi) as IMetaStockFranchiseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStockFranchise {
    return new Contract(address, _abi, signerOrProvider) as IMetaStockFranchise;
  }
}
