/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStocksFranchiseShare,
  IMetaStocksFranchiseShareInterface,
} from "../IMetaStocksFranchiseShare";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStocksFranchiseShare__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStocksFranchiseShareInterface {
    return new utils.Interface(_abi) as IMetaStocksFranchiseShareInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStocksFranchiseShare {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMetaStocksFranchiseShare;
  }
}
