/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaStockCompanyInfo,
  IMetaStockCompanyInfoInterface,
} from "../IMetaStockCompanyInfo";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaStockCompanyInfo__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaStockCompanyInfoInterface {
    return new utils.Interface(_abi) as IMetaStockCompanyInfoInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaStockCompanyInfo {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMetaStockCompanyInfo;
  }
}
