/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IMetaStocksFranchiseManagerInterface extends ethers.utils.Interface {
  functions: {
    "claimFromAllFranchises(uint256)": FunctionFragment;
    "claimFromAllFranchisesBNB(uint256)": FunctionFragment;
    "createMetaStocksFranchise(address,uint256,uint256,uint8)": FunctionFragment;
    "createMetaStocksFranchiseUsingBNB(address,uint256,uint256,uint8)": FunctionFragment;
    "getMetaStocksFranchisesUnclaimedRewards(uint256)": FunctionFragment;
    "hireWorkerUsingBNB(uint256,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimFromAllFranchises",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFromAllFranchisesBNB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMetaStocksFranchise",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMetaStocksFranchiseUsingBNB",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetaStocksFranchisesUnclaimedRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hireWorkerUsingBNB",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimFromAllFranchises",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFromAllFranchisesBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMetaStocksFranchise",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMetaStocksFranchiseUsingBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetaStocksFranchisesUnclaimedRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hireWorkerUsingBNB",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMetaStocksFranchiseManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IMetaStocksFranchiseManagerInterface;

  functions: {
    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimFromAllFranchisesBNB(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  claimFromAllFranchises(
    _companyId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimFromAllFranchisesBNB(
    _companyId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createMetaStocksFranchise(
    to: string,
    companyId: BigNumberish,
    _continentId: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createMetaStocksFranchiseUsingBNB(
    to: string,
    companyId: BigNumberish,
    _continentId: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getMetaStocksFranchisesUnclaimedRewards(
    companyId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hireWorkerUsingBNB(
    companyId: BigNumberish,
    _metaStocksFranchiseType: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimFromAllFranchisesBNB(
      _companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimFromAllFranchisesBNB(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimFromAllFranchises(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimFromAllFranchisesBNB(
      _companyId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createMetaStocksFranchise(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createMetaStocksFranchiseUsingBNB(
      to: string,
      companyId: BigNumberish,
      _continentId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getMetaStocksFranchisesUnclaimedRewards(
      companyId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hireWorkerUsingBNB(
      companyId: BigNumberish,
      _metaStocksFranchiseType: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
